name: Deploy Python package

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_weatherStation:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python for build check
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
  deploy_weatherStation:
    needs: build_weatherStation
    runs-on: [self-hosted, linux]
    environment: production
    env:
      API_KEY_WEATHER:  ${{ secrets.API_KEY_WEATHER }}
      API_KEY_NEWS:  ${{ secrets.API_KEY_NEWS }}
      APP_DIR: ${{ vars.APP_DIR }}
    steps:
      - name: Set up Python for deployment
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: deploy Weather Station
        run: echo "Trying to Deploy"
      - name: Remove app directory ${{ vars.APP_DIR }}
        run:  ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} 'if [ -d "/opt/weather_station" ]; then echo "Weather Station Dir found, deleting"; sudo rm -fR /opt/weather_station; else echo "No weather station directory"; fi'
      - name: Cloning Weather Station
        run: ssh ${{ vars.USER }}@${{ vars.HOSTNAME }} "sudo git clone https://github.com/Ian-s-Company/weather_station.git ${{ vars.APP_DIR }};sudo chmod +x ${{ vars.APP_DIR }}/weather-station*.sh"
      - name: APT and LibraryUpdate
        run: ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} "sudo apt update; sudo apt -y upgrade:python -m venv weather_station_venv;source weather_station_venv/bin/activate;pip install requests pillow gpiozero pytest;"
      - name: Test Weather API
        run: | 
          export API_KEY_WEATHER=${{ secrets.API_KEY_WEATHER }}
          pytest tests/test_weatherapi.py
      - name: Setup Waveshare Config File
        run: | 
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} apt install python3-venv 
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} python -m venv weather_station_venv
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} source weather_station_venv/bin/activate
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "cd /tmp" > /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "if [ -d '/tmp/waveshare' }; then rm -R /tmp/waveshare; fi" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "mkdir -p /tmp/waveshare" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "cd waveshare" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "wget https://github.com/joan2937/lg/archive/master.zip" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.71.tar.gz" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "wget https://project-downloads.drogon.net/wiringpi-latest.deb" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "git clone https://github.com/WiringPi/WiringPi" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "unzip master.zip" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "tar zxvf bcm2835-1.71.tar.gz" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "cd /tmp/waveshare/lg-master" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "make" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "sudo make install" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "sudo apt install gpiod libgpiod-dev wiringpi" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "cd /tmp/waveshare/bcm2835-1.71/" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "sudo ./configure && sudo make && sudo make check && sudo make install" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "sudo dpkg -i wiringpi-latest.deb" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "gpio -v" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "cd /tmp/waveshare/WiringPi" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} echo "./build" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }}  echo "gpio -v" > /tmp/waveshare_config.sh" >> /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} chmod +x /tmp/waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} cd /tmp
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} ./waveshare_config.sh
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} sed -i '/dtparam=spi=no/dtparam=spi=yes/g' /boot/config.txt
          ssh -v ${{ vars.USER }}@${{ vars.HOSTNAME }} reboot         
          sleep 120
      - name: Starting Weather Station
        run: python ${{ vars.APP_DIR }}/weatherStation_main.py ${{ secrets.API_KEY_WEATHER }} ${{ secrets.API_KEY_NEWS }}
