name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    #runs-on: codebuild-myProject-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-fleet-myFleet
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
